# Generated by Django 3.1.3 on 2023-01-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('visitor', 'visitor'), ('student', 'student')], default='employee', max_length=20, null=True),
        ),
    ]
