# Generated by Django 3.1.3 on 2023-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230131_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ranking',
            new_name='roomno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='hostelname',
            field=models.CharField(choices=[('cvr', 'cvr'), ('asr', 'asr'), ('vvk', 'vvk')], default='employee', max_length=20, null=True),
        ),
    ]
