# Generated by Django 3.1.3 on 2023-01-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230131_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostelname',
            field=models.CharField(choices=[('None', 'None'), ('cvr', 'cvr'), ('asr', 'asr'), ('vvk', 'vvk')], default='employee', max_length=20, null=True),
        ),
    ]
